// <auto-generated />
using System;
using GestionMagasin.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestionMagasin.Infrastructure.Migrations
{
    [DbContext(typeof(ContexteMagasin))]
    [Migration("20260823095900_CategoriesEtSystemesTailles")]
    partial class CategoriesEtSystemesTailles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("sequence_numero_achat");

            modelBuilder.HasSequence("sequence_numero_retour");

            modelBuilder.HasSequence("sequence_numero_vente");

            modelBuilder.Entity("GestionMagasin.Domain.Entities.Achat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAchat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_achat");

                    b.Property<DateTime?>("DateReception")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_reception");

                    b.Property<int>("FournisseurId")
                        .HasColumnType("integer")
                        .HasColumnName("fournisseur_id");

                    b.Property<decimal>("MontantPaye")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("montant_paye");

                    b.Property<decimal>("MontantRestant")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("montant_restant");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<string>("NumeroAchat")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("numero_achat");

                    b.Property<decimal>("Remise")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("remise");

                    b.Property<decimal>("SousTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("sous_total");

                    b.Property<int>("Statut")
                        .HasColumnType("integer")
                        .HasColumnName("statut");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("integer")
                        .HasColumnName("utilisateur_id");

                    b.HasKey("Id")
                        .HasName("pk_achats");

                    b.HasIndex("DateAchat")
                        .HasDatabaseName("ix_achats_date_achat");

                    b.HasIndex("FournisseurId")
                        .HasDatabaseName("ix_achats_fournisseur_id");

                    b.HasIndex("NumeroAchat")
                        .IsUnique()
                        .HasDatabaseName("ix_achats_numero_achat");

                    b.HasIndex("Statut")
                        .HasDatabaseName("ix_achats_statut");

                    b.HasIndex("UtilisateurId")
                        .HasDatabaseName("ix_achats_utilisateur_id");

                    b.ToTable("achats", null, t =>
                        {
                            t.HasCheckConstraint("ck_achats_montants_positifs", "sous_total >= 0 AND remise >= 0 AND total >= 0 AND montant_paye >= 0");
                        });
                });

            modelBuilder.Entity("GestionMagasin.Domain.Entities.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("actif");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nom");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer")
                        .HasColumnName("ordre");

                    b.Property<int>("SystemeTailleId")
                        .HasColumnType("integer")
                        .HasColumnName("systeme_taille_id");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("Nom")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_nom");

                    b.HasIndex("Ordre")
                        .HasDatabaseName("ix_categories_ordre");

                    b.HasIndex("SystemeTailleId")
                        .HasDatabaseName("ix_categories_systeme_taille_id");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("GestionMagasin.Domain.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("actif");

                    b.Property<string>("Adresse")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("adresse");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_creation");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nom");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<string>("Prenom")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prenom");

                    b.Property<string>("Telephone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telephone");

                    b.HasKey("Id")
                        .HasName("pk_clients");

                    b.HasIndex("Actif")
                        .HasDatabaseName("ix_clients_actif");

                    b.HasIndex("Nom")
                        .HasDatabaseName("ix_clients_nom");

                    b.HasIndex("Telephone")
                        .HasDatabaseName("ix_clients_telephone");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("GestionMagasin.Domain.Entities.Couleur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("actif");

                    b.Property<string>("CodeCouleur")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("code_couleur");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nom");

                    b.HasKey("Id")
                        .HasName("pk_couleurs");

                    b.HasIndex("Nom")
                        .IsUnique()
                        .HasDatabaseName("ix_couleurs_nom");

                    b.ToTable("couleurs", (string)null);
                });

            modelBuilder.Entity("GestionMagasin.Domain.Entities.Fournisseur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("actif");

                    b.Property<string>("Adresse")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("adresse");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_creation");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Entreprise")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("entreprise");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nom");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<string>("Telephone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telephone");

                    b.HasKey("Id")
                        .HasName("pk_fournisseurs");

                    b.HasIndex("Actif")
                        .HasDatabaseName("ix_fournisseurs_actif");

                    b.HasIndex("Nom")
                        .HasDatabaseName("ix_fournisseurs_nom");

                    b.HasIndex("Telephone")
                        .HasDatabaseName("ix_fournisseurs_telephone");

                    b.ToTable("fournisseurs", (string)null);
                });

            modelBuilder.Entity("GestionMagasin.Domain.Entities.Inventaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_modification");

                    b.Property<int>("QuantiteDisponible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("quantite_disponible");

                    b.Property<int>("VarianteProduitId")
                        .HasColumnType("integer")
                        .HasColumnName("variante_produit_id");

                    b.Property<uint>("VersionEnregistrement")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_inventaires");

                    b.HasIndex("VarianteProduitId")
                        .IsUnique()
                        .HasDatabaseName("ux_inventaires_variante");

                    b.ToTable("inventaires", null, t =>
                        {
                            t.HasCheckConstraint("ck_inventaires_quantite_positive", "quantite_disponible >= 0");
                        });
                });

            modelBuilder.Entity("GestionMagasin.Domain.Entities.JournalAudit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("action");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_creation");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<int?>("EntiteId")
                        .HasColumnType("integer")
                        .HasColumnName("entite_id");

                    b.Property<string>("TypeEntite")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("type_entite");

                    b.Property<int?>("UtilisateurId")
                        .HasColumnType("integer")
                        .HasColumnName("utilisateur_id");

                    b.HasKey("Id")
                        .HasName("pk_journaux_audit");

                    b.HasIndex("DateCreation")
                        .HasDatabaseName("ix_journaux_audit_date_creation");

                    b.HasIndex("UtilisateurId")
                        .HasDatabaseName("ix_journaux_audit_utilisateur_id");

                    b.HasIndex("TypeEntite", "EntiteId")
                        .HasDatabaseName("ix_journaux_audit_type_entite_entite_id");

                    b.ToTable("journaux_audit", (string)null);
                });

            modelBuilder.Entity("GestionMagasin.Domain.Entities.LigneAchat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AchatId")
                        .HasColumnType("integer")
                        .HasColumnName("achat_id");

                    b.Property<decimal>("PrixUnitaire")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("prix_unitaire");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer")
                        .HasColumnName("quantite");

                    b.Property<int>("QuantiteRecue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("quantite_recue");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total");

                    b.Property<int>("VarianteProduitId")
                        .HasColumnType("integer")
                        .HasColumnName("variante_produit_id");

                    b.HasKey("Id")
                        .HasName("pk_lignes_achat");

                    b.HasIndex("AchatId")
                        .HasDatabaseName("ix_lignes_achat_achat_id");

                    b.HasIndex("VarianteProduitId")
                        .HasDatabaseName("ix_lignes_achat_variante_produit_id");

                    b.ToTable("lignes_achat", null, t =>
                        {
                            t.HasCheckConstraint("ck_lignes_achat_prix_positif", "prix_unitaire >= 0");

                            t.HasCheckConstraint("ck_lignes_achat_quantite_positive", "quantite > 0");

                            t.HasCheckConstraint("ck_lignes_achat_recue_coherente", "quantite_recue >= 0 AND quantite_recue <= quantite");
                        });
                });

            modelBuilder.Entity("GestionMagasin.Domain.Entities.LigneRetour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EtatArticle")
                        .HasColumnType("integer")
                        .HasColumnName("etat_article");

                    b.Property<int>("LigneVenteId")
                        .HasColumnType("integer")
                        .HasColumnName("ligne_vente_id");

                    b.Property<decimal>("MontantRembourse")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("montant_rembourse");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer")
                        .HasColumnName("quantite");

                    b.Property<bool>("RemisEnStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("remis_en_stock");

                    b.Property<int>("RetourId")
                        .HasColumnType("integer")
                        .HasColumnName("retour_id");

                    b.Property<int>("VarianteProduitId")
                        .HasColumnType("integer")
                        .HasColumnName("variante_produit_id");

                    b.HasKey("Id")
                        .HasName("pk_lignes_retour");

                    b.HasIndex("LigneVenteId")
                        .HasDatabaseName("ix_lignes_retour_ligne_vente_id");

                    b.HasIndex("RetourId")
                        .HasDatabaseName("ix_lignes_retour_retour_id");

                    b.HasIndex("VarianteProduitId")
                        .HasDatabaseName("ix_lignes_retour_variante_produit_id");

                    b.ToTable("lignes_retour", null, t =>
                        {
                            t.HasCheckConstraint("ck_lignes_retour_etat_coherent", "remis_en_stock = false OR etat_article = 1");

                            t.HasCheckConstraint("ck_lignes_retour_montant_positif", "montant_rembourse >= 0");

                            t.HasCheckConstraint("ck_lignes_retour_quantite_positive", "quantite > 0");
                        });
                });

            modelBuilder.Entity("GestionMagasin.Domain.Entities.LigneVente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("PrixAchatUnitaire")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("prix_achat_unitaire");

                    b.Property<decimal>("PrixUnitaire")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("prix_unitaire");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer")
                        .HasColumnName("quantite");

                    b.Property<int>("QuantiteRetournee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("quantite_retournee");

                    b.Property<decimal>("Remise")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("remise");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total");

                    b.Property<int>("VarianteProduitId")
                        .HasColumnType("integer")
                        .HasColumnName("variante_produit_id");

                    b.Property<int>("VenteId")
                        .HasColumnType("integer")
                        .HasColumnName("vente_id");

                    b.HasKey("Id")
                        .HasName("pk_lignes_vente");

                    b.HasIndex("VarianteProduitId")
                        .HasDatabaseName("ix_lignes_vente_variante_produit_id");

                    b.HasIndex("VenteId")
                        .HasDatabaseName("ix_lignes_vente_vente_id");

                    b.ToTable("lignes_vente", null, t =>
                        {
                            t.HasCheckConstraint("ck_lignes_vente_prix_positif", "prix_unitaire >= 0 AND remise >= 0");

                            t.HasCheckConstraint("ck_lignes_vente_quantite_positive", "quantite > 0");

                            t.HasCheckConstraint("ck_lignes_vente_retour_coherent", "quantite_retournee >= 0 AND quantite_retournee <= quantite");
                        });
                });

            modelBuilder.Entity("GestionMagasin.Domain.Entities.Marque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("actif");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nom");

                    b.HasKey("Id")
                        .HasName("pk_marques");

                    b.HasIndex("Nom")
                        .IsUnique()
                        .HasDatabaseName("ix_marques_nom");

                    b.ToTable("marques", (string)null);
                });

            modelBuilder.Entity("GestionMagasin.Domain.Entities.MouvementStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AncienneQuantite")
                        .HasColumnType("integer")
                        .HasColumnName("ancienne_quantite");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_creation");

                    b.Property<string>("Motif")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("motif");

                    b.Property<int>("NouvelleQuantite")
                        .HasColumnType("integer")
                        .HasColumnName("nouvelle_quantite");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer")
                        .HasColumnName("quantite");

                    b.Property<string>("ReferenceDocument")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("reference_document");

                    b.Property<int>("TypeMouvement")
                        .HasColumnType("integer")
                        .HasColumnName("type_mouvement");

                    b.Property<int?>("UtilisateurId")
                        .HasColumnType("integer")
                        .HasColumnName("utilisateur_id");

                    b.Property<int>("VarianteProduitId")
                        .HasColumnType("integer")
                        .HasColumnName("variante_produit_id");

                    b.HasKey("Id")
                        .HasName("pk_mouvements_stock");

                    b.HasIndex("DateCreation")
                        .HasDatabaseName("ix_mouvements_stock_date_creation");

                    b.HasIndex("ReferenceDocument")
                        .HasDatabaseName("ix_mouvements_stock_reference_document");

                    b.HasIndex("TypeMouvement")
                        .HasDatabaseName("ix_mouvements_stock_type_mouvement");

                    b.HasIndex("UtilisateurId")
                        .HasDatabaseName("ix_mouvements_stock_utilisateur_id");

                    b.HasIndex("VarianteProduitId", "DateCreation")
                        .HasDatabaseName("ix_mouvements_stock_variante_produit_id_date_creation");

                    b.ToTable("mouvements_stock", (string)null);
                });

            modelBuilder.Entity("GestionMagasin.Domain.Entities.Paiement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatePaiement")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_paiement");

                    b.Property<int>("ModePaiement")
                        .HasColumnType("integer")
                        .HasColumnName("mode_paiement");

                    b.Property<decimal>("Montant")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("montant");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference");

                    b.Property<int>("VenteId")
                        .HasColumnType("integer")
                        .HasColumnName("vente_id");

                    b.HasKey("Id")
                        .HasName("pk_paiements");

                    b.HasIndex("DatePaiement")
                        .HasDatabaseName("ix_paiements_date_paiement");

                    b.HasIndex("ModePaiement")
                        .HasDatabaseName("ix_paiements_mode_paiement");

                    b.HasIndex("VenteId")
                        .HasDatabaseName("ix_paiements_vente_id");

                    b.ToTable("paiements", null, t =>
                        {
                            t.HasCheckConstraint("ck_paiements_montant_positif", "montant > 0");
                        });
                });

            modelBuilder.Entity("GestionMagasin.Domain.Entities.ParametresMagasin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("adresse");

                    b.Property<string>("ArticleImposition")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("article_imposition");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_modification");

                    b.Property<int>("DelaiRetourJours")
                        .HasColumnType("integer")
                        .HasColumnName("delai_retour_jours");

                    b.Property<string>("Devise")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("DZD")
                        .HasColumnName("devise");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("InformationsTicket")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("informations_ticket");

                    b.Property<string>("Logo")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("logo");

                    b.Property<string>("NomMagasin")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nom_magasin");

                    b.Property<string>("NumeroIdentificationFiscale")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("numero_identification_fiscale");

                    b.Property<string>("RegistreCommerce")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("registre_commerce");

                    b.Property<string>("SymboleDevise")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("DA")
                        .HasColumnName("symbole_devise");

                    b.Property<decimal>("TauxTva")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("taux_tva");

                    b.Property<string>("Telephone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telephone");

                    b.HasKey("Id")
                        .HasName("pk_parametres_magasin");

                    b.ToTable("parametres_magasin", null, t =>
                        {
                            t.HasCheckConstraint("ck_parametres_delai_retour_positif", "delai_retour_jours >= 0");

                            t.HasCheckConstraint("ck_parametres_ligne_unique", "id = 1");

                            t.HasCheckConstraint("ck_parametres_tva_valide", "taux_tva >= 0 AND taux_tva <= 100");
                        });
                });

            modelBuilder.Entity("GestionMagasin.Domain.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("categorie");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nom");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_permissions_code");

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("GestionMagasin.Domain.Entities.Produit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("actif");

                    b.Property<int>("CategorieId")
                        .HasColumnType("integer")
                        .HasColumnName("categorie_id");

                    b.Property<string>("Collection")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("collection");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_creation");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_modification");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<int?>("MarqueId")
                        .HasColumnType("integer")
                        .HasColumnName("marque_id");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nom");

                    b.Property<string>("Photo")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("photo");

                    b.Property<decimal>("PrixAchat")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("prix_achat");

                    b.Property<decimal>("PrixVente")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("prix_vente");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("reference");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("sku");

                    b.Property<string>("Saison")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("saison");

                    b.HasKey("Id")
                        .HasName("pk_produits");

                    b.HasIndex("Actif")
                        .HasDatabaseName("ix_produits_actif");

                    b.HasIndex("CategorieId")
                        .HasDatabaseName("ix_produits_categorie_id");

                    b.HasIndex("MarqueId")
                        .HasDatabaseName("ix_produits_marque_id");

                    b.HasIndex("Nom")
                        .HasDatabaseName("ix_produits_nom");

                    b.HasIndex("Reference")
                        .IsUnique()
                        .HasDatabaseName("ix_produits_reference");

                    b.HasIndex("SKU")
                        .IsUnique()
                        .HasDatabaseName("ix_produits_sku");

                    b.ToTable("produits", null, t =>
                        {
                            t.HasCheckConstraint("ck_produits_prix_achat_positif", "prix_achat >= 0");

                            t.HasCheckConstraint("ck_produits_prix_vente_positif", "prix_vente >= 0");
                        });
                });

            modelBuilder.Entity("GestionMagasin.Domain.Entities.Retour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("DateRetour")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_retour");

                    b.Property<string>("Motif")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("motif");

                    b.Property<string>("NumeroRetour")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("numero_retour");

                    b.Property<int>("Statut")
                        .HasColumnType("integer")
                        .HasColumnName("statut");

                    b.Property<decimal>("TotalRembourse")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_rembourse");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("integer")
                        .HasColumnName("utilisateur_id");

                    b.Property<int>("VenteId")
                        .HasColumnType("integer")
                        .HasColumnName("vente_id");

                    b.HasKey("Id")
                        .HasName("pk_retours");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_retours_client_id");

                    b.HasIndex("DateRetour")
                        .HasDatabaseName("ix_retours_date_retour");

                    b.HasIndex("NumeroRetour")
                        .IsUnique()
                        .HasDatabaseName("ix_retours_numero_retour");

                    b.HasIndex("UtilisateurId")
                        .HasDatabaseName("ix_retours_utilisateur_id");

                    b.HasIndex("VenteId")
                        .HasDatabaseName("ix_retours_vente_id");

                    b.ToTable("retours", null, t =>
                        {
                            t.HasCheckConstraint("ck_retours_montant_positif", "total_rembourse >= 0");
                        });
                });

            modelBuilder.Entity("GestionMagasin.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<bool>("EstSysteme")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("est_systeme");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("nom");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Nom")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_nom");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("GestionMagasin.Domain.Entities.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_role_permissions");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_role_permissions_permission_id");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("GestionMagasin.Domain.Entities.SystemeTaille", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("actif");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nom");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer")
                        .HasColumnName("ordre");

                    b.HasKey("Id")
                        .HasName("pk_systemes_tailles");

                    b.HasIndex("Nom")
                        .IsUnique()
                        .HasDatabaseName("ix_systemes_tailles_nom");

                    b.HasIndex("Ordre")
                        .HasDatabaseName("ix_systemes_tailles_ordre");

                    b.ToTable("systemes_tailles", (string)null);
                });

            modelBuilder.Entity("GestionMagasin.Domain.Entities.Taille", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("actif");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nom");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer")
                        .HasColumnName("ordre");

                    b.Property<int>("SystemeTailleId")
                        .HasColumnType("integer")
                        .HasColumnName("systeme_taille_id");

                    b.HasKey("Id")
                        .HasName("pk_tailles");

                    b.HasIndex("Ordre")
                        .HasDatabaseName("ix_tailles_ordre");

                    b.HasIndex("SystemeTailleId", "Nom")
                        .IsUnique()
                        .HasDatabaseName("ix_tailles_systeme_taille_id_nom");

                    b.ToTable("tailles", (string)null);
                });

            modelBuilder.Entity("GestionMagasin.Domain.Entities.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("actif");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_creation");

                    b.Property<DateTime?>("DerniereConnexion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("derniere_connexion");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nom");

                    b.Property<string>("NomUtilisateur")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("nom_utilisateur");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("prenom");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_utilisateurs");

                    b.HasIndex("NomUtilisateur")
                        .IsUnique()
                        .HasDatabaseName("ix_utilisateurs_nom_utilisateur");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_utilisateurs_role_id");

                    b.ToTable("utilisateurs", (string)null);
                });

            modelBuilder.Entity("GestionMagasin.Domain.Entities.VarianteProduit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("actif");

                    b.Property<string>("CodeBarres")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("code_barres");

                    b.Property<int>("CouleurId")
                        .HasColumnType("integer")
                        .HasColumnName("couleur_id");

                    b.Property<decimal?>("PrixAchat")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("prix_achat");

                    b.Property<decimal?>("PrixVente")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("prix_vente");

                    b.Property<int>("ProduitId")
                        .HasColumnType("integer")
                        .HasColumnName("produit_id");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("sku");

                    b.Property<int>("SeuilMinimum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("seuil_minimum");

                    b.Property<int>("TailleId")
                        .HasColumnType("integer")
                        .HasColumnName("taille_id");

                    b.HasKey("Id")
                        .HasName("pk_variantes_produits");

                    b.HasIndex("CodeBarres")
                        .IsUnique()
                        .HasDatabaseName("ux_variantes_code_barres")
                        .HasFilter("code_barres IS NOT NULL");

                    b.HasIndex("CouleurId")
                        .HasDatabaseName("ix_variantes_produits_couleur_id");

                    b.HasIndex("SKU")
                        .IsUnique()
                        .HasDatabaseName("ix_variantes_produits_sku");

                    b.HasIndex("TailleId")
                        .HasDatabaseName("ix_variantes_produits_taille_id");

                    b.HasIndex("ProduitId", "TailleId", "CouleurId")
                        .IsUnique()
                        .HasDatabaseName("ux_variantes_produit_taille_couleur");

                    b.ToTable("variantes_produits", null, t =>
                        {
                            t.HasCheckConstraint("ck_variantes_prix_achat_positif", "prix_achat IS NULL OR prix_achat >= 0");

                            t.HasCheckConstraint("ck_variantes_prix_vente_positif", "prix_vente IS NULL OR prix_vente >= 0");

                            t.HasCheckConstraint("ck_variantes_seuil_positif", "seuil_minimum >= 0");
                        });
                });

            modelBuilder.Entity("GestionMagasin.Domain.Entities.Vente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("DateVente")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_vente");

                    b.Property<decimal>("MontantPaye")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("montant_paye");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<string>("NumeroVente")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("numero_vente");

                    b.Property<decimal>("Remise")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("remise");

                    b.Property<decimal>("SousTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("sous_total");

                    b.Property<int>("Statut")
                        .HasColumnType("integer")
                        .HasColumnName("statut");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("integer")
                        .HasColumnName("utilisateur_id");

                    b.HasKey("Id")
                        .HasName("pk_ventes");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_ventes_client_id");

                    b.HasIndex("DateVente")
                        .HasDatabaseName("ix_ventes_date_vente");

                    b.HasIndex("NumeroVente")
                        .IsUnique()
                        .HasDatabaseName("ix_ventes_numero_vente");

                    b.HasIndex("Statut")
                        .HasDatabaseName("ix_ventes_statut");

                    b.HasIndex("UtilisateurId")
                        .HasDatabaseName("ix_ventes_utilisateur_id");

                    b.ToTable("ventes", null, t =>
                        {
                            t.HasCheckConstraint("ck_ventes_montants_positifs", "sous_total >= 0 AND remise >= 0 AND total >= 0 AND montant_paye >= 0");
                        });
                });

            modelBuilder.Entity("GestionMagasin.Domain.Entities.Achat", b =>
                {
                    b.HasOne("GestionMagasin.Domain.Entities.Fournisseur", "Fournisseur")
                        .WithMany("Achats")
                        .HasForeignKey("FournisseurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_achats_fournisseurs_fournisseur_id");

                    b.HasOne("GestionMagasin.Domain.Entities.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_achats_utilisateurs_utilisateur_id");

                    b.Navigation("Fournisseur");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("GestionMagasin.Domain.Entities.Categorie", b =>
                {
                    b.HasOne("GestionMagasin.Domain.Entities.SystemeTaille", "SystemeTaille")
                        .WithMany("Categories")
                        .HasForeignKey("SystemeTailleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_categories_systemes_tailles_systeme_taille_id");

                    b.Navigation("SystemeTaille");
                });

            modelBuilder.Entity("GestionMagasin.Domain.Entities.Inventaire", b =>
                {
                    b.HasOne("GestionMagasin.Domain.Entities.VarianteProduit", "VarianteProduit")
                        .WithOne("Inventaire")
                        .HasForeignKey("GestionMagasin.Domain.Entities.Inventaire", "VarianteProduitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventaires_variantes_produits_variante_produit_id");

                    b.Navigation("VarianteProduit");
                });

            modelBuilder.Entity("GestionMagasin.Domain.Entities.JournalAudit", b =>
                {
                    b.HasOne("GestionMagasin.Domain.Entities.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_journaux_audit_utilisateurs_utilisateur_id");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("GestionMagasin.Domain.Entities.LigneAchat", b =>
                {
                    b.HasOne("GestionMagasin.Domain.Entities.Achat", "Achat")
                        .WithMany("Lignes")
                        .HasForeignKey("AchatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lignes_achat_achats_achat_id");

                    b.HasOne("GestionMagasin.Domain.Entities.VarianteProduit", "VarianteProduit")
                        .WithMany()
                        .HasForeignKey("VarianteProduitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lignes_achat_variantes_produits_variante_produit_id");

                    b.Navigation("Achat");

                    b.Navigation("VarianteProduit");
                });

            modelBuilder.Entity("GestionMagasin.Domain.Entities.LigneRetour", b =>
                {
                    b.HasOne("GestionMagasin.Domain.Entities.LigneVente", "LigneVente")
                        .WithMany()
                        .HasForeignKey("LigneVenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lignes_retour_lignes_vente_ligne_vente_id");

                    b.HasOne("GestionMagasin.Domain.Entities.Retour", "Retour")
                        .WithMany("Lignes")
                        .HasForeignKey("RetourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lignes_retour_retours_retour_id");

                    b.HasOne("GestionMagasin.Domain.Entities.VarianteProduit", "VarianteProduit")
                        .WithMany()
                        .HasForeignKey("VarianteProduitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lignes_retour_variantes_produits_variante_produit_id");

                    b.Navigation("LigneVente");

                    b.Navigation("Retour");

                    b.Navigation("VarianteProduit");
                });

            modelBuilder.Entity("GestionMagasin.Domain.Entities.LigneVente", b =>
                {
                    b.HasOne("GestionMagasin.Domain.Entities.VarianteProduit", "VarianteProduit")
                        .WithMany()
                        .HasForeignKey("VarianteProduitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lignes_vente_variantes_produits_variante_produit_id");

                    b.HasOne("GestionMagasin.Domain.Entities.Vente", "Vente")
                        .WithMany("Lignes")
                        .HasForeignKey("VenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lignes_vente_ventes_vente_id");

                    b.Navigation("VarianteProduit");

                    b.Navigation("Vente");
                });

            modelBuilder.Entity("GestionMagasin.Domain.Entities.MouvementStock", b =>
                {
                    b.HasOne("GestionMagasin.Domain.Entities.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_mouvements_stock_utilisateurs_utilisateur_id");

                    b.HasOne("GestionMagasin.Domain.Entities.VarianteProduit", "VarianteProduit")
                        .WithMany("MouvementsStock")
                        .HasForeignKey("VarianteProduitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_mouvements_stock_variantes_produits_variante_produit_id");

                    b.Navigation("Utilisateur");

                    b.Navigation("VarianteProduit");
                });

            modelBuilder.Entity("GestionMagasin.Domain.Entities.Paiement", b =>
                {
                    b.HasOne("GestionMagasin.Domain.Entities.Vente", "Vente")
                        .WithMany("Paiements")
                        .HasForeignKey("VenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_paiements_ventes_vente_id");

                    b.Navigation("Vente");
                });

            modelBuilder.Entity("GestionMagasin.Domain.Entities.Produit", b =>
                {
                    b.HasOne("GestionMagasin.Domain.Entities.Categorie", "Categorie")
                        .WithMany("Produits")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_produits_categories_categorie_id");

                    b.HasOne("GestionMagasin.Domain.Entities.Marque", "Marque")
                        .WithMany("Produits")
                        .HasForeignKey("MarqueId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_produits_marques_marque_id");

                    b.Navigation("Categorie");

                    b.Navigation("Marque");
                });

            modelBuilder.Entity("GestionMagasin.Domain.Entities.Retour", b =>
                {
                    b.HasOne("GestionMagasin.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_retours_clients_client_id");

                    b.HasOne("GestionMagasin.Domain.Entities.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_retours_utilisateurs_utilisateur_id");

                    b.HasOne("GestionMagasin.Domain.Entities.Vente", "Vente")
                        .WithMany("Retours")
                        .HasForeignKey("VenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_retours_ventes_vente_id");

                    b.Navigation("Client");

                    b.Navigation("Utilisateur");

                    b.Navigation("Vente");
                });

            modelBuilder.Entity("GestionMagasin.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("GestionMagasin.Domain.Entities.Permission", "Permission")
                        .WithMany("Roles")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_id");

                    b.HasOne("GestionMagasin.Domain.Entities.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_id");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("GestionMagasin.Domain.Entities.Taille", b =>
                {
                    b.HasOne("GestionMagasin.Domain.Entities.SystemeTaille", "SystemeTaille")
                        .WithMany("Tailles")
                        .HasForeignKey("SystemeTailleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tailles_systemes_tailles_systeme_taille_id");

                    b.Navigation("SystemeTaille");
                });

            modelBuilder.Entity("GestionMagasin.Domain.Entities.Utilisateur", b =>
                {
                    b.HasOne("GestionMagasin.Domain.Entities.Role", "Role")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_utilisateurs_roles_role_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("GestionMagasin.Domain.Entities.VarianteProduit", b =>
                {
                    b.HasOne("GestionMagasin.Domain.Entities.Couleur", "Couleur")
                        .WithMany("Variantes")
                        .HasForeignKey("CouleurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_variantes_produits_couleurs_couleur_id");

                    b.HasOne("GestionMagasin.Domain.Entities.Produit", "Produit")
                        .WithMany("Variantes")
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_variantes_produits_produits_produit_id");

                    b.HasOne("GestionMagasin.Domain.Entities.Taille", "Taille")
                        .WithMany("Variantes")
                        .HasForeignKey("TailleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_variantes_produits_tailles_taille_id");

                    b.Navigation("Couleur");

                    b.Navigation("Produit");

                    b.Navigation("Taille");
                });

            modelBuilder.Entity("GestionMagasin.Domain.Entities.Vente", b =>
                {
                    b.HasOne("GestionMagasin.Domain.Entities.Client", "Client")
                        .WithMany("Ventes")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ventes_clients_client_id");

                    b.HasOne("GestionMagasin.Domain.Entities.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ventes_utilisateurs_utilisateur_id");

                    b.Navigation("Client");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("GestionMagasin.Domain.Entities.Achat", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("GestionMagasin.Domain.Entities.Categorie", b =>
                {
                    b.Navigation("Produits");
                });

            modelBuilder.Entity("GestionMagasin.Domain.Entities.Client", b =>
                {
                    b.Navigation("Ventes");
                });

            modelBuilder.Entity("GestionMagasin.Domain.Entities.Couleur", b =>
                {
                    b.Navigation("Variantes");
                });

            modelBuilder.Entity("GestionMagasin.Domain.Entities.Fournisseur", b =>
                {
                    b.Navigation("Achats");
                });

            modelBuilder.Entity("GestionMagasin.Domain.Entities.Marque", b =>
                {
                    b.Navigation("Produits");
                });

            modelBuilder.Entity("GestionMagasin.Domain.Entities.Permission", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("GestionMagasin.Domain.Entities.Produit", b =>
                {
                    b.Navigation("Variantes");
                });

            modelBuilder.Entity("GestionMagasin.Domain.Entities.Retour", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("GestionMagasin.Domain.Entities.Role", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("GestionMagasin.Domain.Entities.SystemeTaille", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Tailles");
                });

            modelBuilder.Entity("GestionMagasin.Domain.Entities.Taille", b =>
                {
                    b.Navigation("Variantes");
                });

            modelBuilder.Entity("GestionMagasin.Domain.Entities.VarianteProduit", b =>
                {
                    b.Navigation("Inventaire");

                    b.Navigation("MouvementsStock");
                });

            modelBuilder.Entity("GestionMagasin.Domain.Entities.Vente", b =>
                {
                    b.Navigation("Lignes");

                    b.Navigation("Paiements");

                    b.Navigation("Retours");
                });
#pragma warning restore 612, 618
        }
    }
}
