<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>GestionMagasin.App</RootNamespace>
    <AssemblyName>GestionMagasin</AssemblyName>
    <ApplicationIcon />
    <SatelliteResourceLanguages>fr</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.11" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GestionMagasin.Domain\GestionMagasin.Domain.csproj" />
    <ProjectReference Include="..\GestionMagasin.Application\GestionMagasin.Application.csproj" />
    <ProjectReference Include="..\GestionMagasin.Infrastructure\GestionMagasin.Infrastructure.csproj" />
    <ProjectReference Include="..\GestionMagasin.ServeurEmbarque\GestionMagasin.ServeurEmbarque.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
